
# This file is automatically generated, you probably don't want to edit this

tableoneOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "tableoneOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            vars = NULL,
            sty = "t1", ...) {

            super$initialize(
                package='ClinicoPath',
                name='tableone',
                requiresData=TRUE,
                ...)

            private$..vars <- jmvcore::OptionVariables$new(
                "vars",
                vars)
            private$..sty <- jmvcore::OptionList$new(
                "sty",
                sty,
                options=list(
                    "t1",
                    "t2"),
                default="t1")

            self$.addOption(private$..vars)
            self$.addOption(private$..sty)
        }),
    active = list(
        vars = function() private$..vars$value,
        sty = function() private$..sty$value),
    private = list(
        ..vars = NA,
        ..sty = NA)
)

tableoneResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        todo = function() private$.items[["todo"]],
        tablestyle1 = function() private$.items[["tablestyle1"]],
        tablestyle2 = function() private$.items[["tablestyle2"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Table One",
                refs=list(
                    "tableone",
                    "gtsummary"))
            self$add(jmvcore::Html$new(
                options=options,
                name="todo",
                title="To Do"))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="tablestyle1",
                title="Table One",
                clearWith=list(
                    "vars"),
                visible="(sty:t1)"))
            self$add(jmvcore::Html$new(
                options=options,
                name="tablestyle2",
                title="Table One",
                clearWith=list(
                    "vars"),
                visible="(sty:t2)"))}))

tableoneBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "tableoneBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'ClinicoPath',
                name = 'tableone',
                version = c(0,0,1),
                options = options,
                results = tableoneResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Table One
#'
#' Function for making Table One.
#'
#' @examples
#' \dontrun{
#' ClinicoPath::tableone(
#' data = data,
#' vars = vars())
#'}
#' @param data The data as a data frame.
#' @param vars a string naming the variables from \code{data} that contains
#'   the values used for the Table One.
#' @param sty .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$todo} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$tablestyle1} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$tablestyle2} \tab \tab \tab \tab \tab a html \cr
#' }
#'
#' @export
tableone <- function(
    data,
    vars,
    sty = "t1") {

    if ( ! requireNamespace('jmvcore'))
        stop('tableone requires jmvcore to be installed (restart may be required)')

    if ( ! missing(vars)) vars <- jmvcore::resolveQuo(jmvcore::enquo(vars))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(vars), vars, NULL))


    options <- tableoneOptions$new(
        vars = vars,
        sty = sty)

    analysis <- tableoneClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
